apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rolling
spec:
  replicas: 6
  selector:
    matchLabels:
     env: production
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
      - name: test
        image: quay.io/shruti1988/production:v1
